/* One representative element per component — shared by the SSR test and the hydration test. */
export function fixtures(A, React) {
  const h = React.createElement;
  const rows = [{ id: 'ORD-1042', name: 'คุณสมชาย ใจดี', status: 'Ready', owner: 'Tao' }, { id: 'ORD-1043', name: 'Anna Lee', status: 'Blocked', owner: 'Mai' }];
  const noop = () => {};
  return {
    Icon: h(A.Icon, { name: 'calendar' }),
    ColorSchemeScript: h(A.ColorSchemeScript, null),
    ColorSchemeToggle: h(A.ColorSchemeToggle, null),
    Button: h(A.Button, { icon: 'plus' }, 'New order'),
    IconButton: h(A.IconButton, { icon: 'ellipsis', label: 'More' }),
    Menu: h(A.Menu, { anchor: null, label: 'Actions', items: [{ label: 'Edit' }], onClose: noop }),
    DropdownMenu: h(A.DropdownMenu, { label: 'Row actions', trigger: h(A.IconButton, { icon: 'ellipsis', label: 'Actions' }), items: [{ label: 'Edit', icon: 'pencil' }] }),
    Checkbox: h(A.Checkbox, { defaultChecked: true, description: 'We email a receipt' }, 'Send receipt'),
    StatusPill: h(A.StatusPill, null, 'Ready'),
    TextField: h(A.TextField, { label: 'ชื่อลูกค้า', hint: 'ชื่อ–นามสกุล' }),
    Textarea: h(A.Textarea, { label: 'Notes' }),
    Select: h(A.Select, { label: 'Category', options: ['Product', 'Service'] }),
    RadioGroup: h(A.RadioGroup, { label: 'Frequency', options: ['Once', 'Weekly'], defaultValue: 'Once' }),
    Switch: h(A.Switch, { label: 'Notify' }),
    Combobox: h(A.Combobox, { label: 'ผู้ดูแล', options: [{ value: 'a', label: 'กมล', keywords: ['kamon'] }, 'Mai'], defaultValue: 'a', clearable: true }),
    DatePicker: h(A.DatePicker, { label: 'วันที่', defaultValue: '2026-09-18', clearable: true }),
    DateRangePicker: h(A.DateRangePicker, { label: 'ช่วงวันที่', defaultValue: { start: '2026-09-01', end: '2026-09-30' } }),
    Calendar: h(A.Calendar, { start: '2026-09-18', focus: '2026-09-18' }),
    Alert: h(A.Alert, { tone: 'warning', title: 'Heads up' }, 'Two orders overlap.'),
    Toaster: h(A.Toaster, null),
    Tooltip: h(A.Tooltip, { content: 'Copy' }, h(A.IconButton, { icon: 'copy', label: 'Copy' })),
    Dialog: h(A.Dialog, { open: true, onClose: noop, title: 'Cancel order?' }, 'Body'),
    Drawer: h(A.Drawer, { open: true, onClose: noop, title: 'ORD-1042' }, 'Detail'),
    DataTable: h(A.DataTable, { rows, selectable: true, stackBelow: 640, pageSize: 10 }),
    Card: h(A.Card, { title: 'Revenue' }, '฿ 42,000'),
    Tabs: h(A.Tabs, { label: 'Filter', tabs: [{ id: 'a', label: 'All', content: 'x' }, { id: 'b', label: 'Today' }] }),
    SideNav: h(A.SideNav, { items: [{ id: 'd', label: 'Dashboard', icon: 'layout-dashboard' }], value: 'd' }),
    Breadcrumb: h(A.Breadcrumb, { items: [{ label: 'Orders', href: '#' }, { label: 'ORD-1042' }] }),
    Avatar: h(A.Avatar, { name: 'Tao P' }),
    Stack: h(A.Stack, { direction: { base: 'column', md: 'row' }, gap: { base: 2, md: 4 } }, 'a', 'b'),
    Grid: h(A.Grid, { columns: { base: 1, md: 2, lg: 4 } }, 'a', 'b'),
    Container: h(A.Container, { size: 'narrow' }, 'c'),
    AppShell: h(A.AppShell, { nav: h(A.SideNav, { items: [{ id: 'd', label: 'Dashboard' }], value: 'd' }), header: 'Orders' }, 'content'),
    Surface: h(A.Surface, { texture: 'mesh' }, 'hero'),
    AuraProvider: h(A.AuraProvider, { locale: 'th' }, h(A.DataTable, { rows, pageSize: 1 }), h(A.DatePicker, { label: 'x', defaultValue: '2026-09-18' })),
    Stat: h(A.Stat, { label: 'Orders', value: '42', unit: 'งาน', change: { value: '+12%', direction: 'up', label: 'vs last month' }, icon: 'calendar' }),
    TimePicker: h(A.TimePicker, { label: 'เวลา', defaultValue: '09:30', min: '08:00', max: '18:00' }),
    FileUpload: h(A.FileUpload, { label: 'รูปหน้างาน', accept: 'image/*', multiple: true, maxSize: 5 * 1024 * 1024, defaultValue: [{ id: 'a', name: 'kitchen.jpg', size: 204800, type: 'image/jpeg', status: 'done' }, { id: 'b', name: 'big.png', size: 9e6, type: 'image/png', status: 'error', error: 'Too big' }] }),
    Badge: h(A.Badge, { tone: 'success', icon: 'check' }, 'Paid'),
    Tag: h(A.Tag, { onRemove: noop }, 'สาขาสยาม'),
    Progress: h(A.Progress, { label: 'Uploading', value: 40, showValue: true }),
    Skeleton: h(A.Skeleton, { lines: 3 }),
    EmptyState: h(A.EmptyState, { icon: 'search', title: 'No results', description: 'Try another filter' }),
    Pagination: h(A.Pagination, { pageCount: 10, defaultPage: 5 }),
    Accordion: h(A.Accordion, { items: [{ id: 'a', title: 'Billing', content: 'x' }, { id: 'b', title: 'Team', content: 'y' }], defaultValue: 'a' }),
    Popover: h(A.Popover, { trigger: h(A.Button, null, 'Filters'), title: 'Filters', defaultOpen: true }, 'content'),
    ThemeStyle: h(A.ThemeStyle, { brand: '#0ea5e9', selector: '.tenant' }),
    Field: h(A.Field, { label: 'Custom', id: 'f1' }, h('input', { id: 'f1' })),
  };
}
