#!/usr/bin/env node
/* Build every token output from tokens.json (the single source of truth).
 *   aura-fonts.css       the Google Fonts @import (kept apart so a blocked font host can't break aura.css)
 *   aura.css             CSS variables: light on :root / [data-theme="light"], dark on .dark / [data-theme="dark"],
 *                        and data-theme="system" follows prefers-color-scheme
 *   tailwind.tokens.cjs  the maps tailwind.config.ts spreads into theme.extend
 *   figma-variables.csv  every colour for both modes + numbers, for a Variables Import plugin
 * Usage: node scripts/build-tokens.js   (npm run build:tokens) */
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const T = JSON.parse(fs.readFileSync(path.join(root, 'tokens.json'), 'utf8'));

const kebab = (s) => String(s).replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
const cssRef = (v) => String(v).replace(/\{primitive\.([a-z]+)(?:\.(\d+))?\}/g, (_, a, b) => `var(--aura-${a}${b ? '-' + b : ''})`)
  .replace(/\{(?:semantic|component)\.([a-z0-9-]+)\}/g, (_, a) => `var(--aura-${a})`);
const figmaRef = (v) => String(v).replace(/\{primitive\.([a-z]+)(?:\.(\d+))?\}/g, (_, a, b) => `{primitive/${a}${b ? '/' + b : ''}}`)
  .replace(/\{(semantic|component)\.([a-z0-9-]+)\}/g, (_, t, a) => `{${t}/${a}}`);
const px = (v) => String(v).replace(/px$/, '');

/* ---------- aura.css ---------- */
const L = [];
L.push('/* AURA v' + T.version + ' — GENERATED by scripts/build-tokens.js from tokens.json. Do not edit by hand. */');
L.push('/* Fonts: load aura-fonts.css (or the <link> tags in README) separately, so a blocked Google Fonts never breaks this file. */', '');
L.push(':root, [data-theme="light"] {');
for (const [fam, scale] of Object.entries(T.primitive)) {
  if (typeof scale === 'string') L.push(`  --aura-${fam}: ${scale};`);
  else for (const [k, v] of Object.entries(scale)) L.push(`  --aura-${fam}-${k}: ${v};`);
}
for (const tier of ['semantic', 'component']) for (const [k, v] of Object.entries(T[tier].light)) L.push(`  --aura-${k}: ${cssRef(v)};`);
for (const [k, v] of Object.entries(T.shadow.light)) L.push(`  --aura-${k}: ${v};`);
L.push('  color-scheme: light;', '}', '');
/* Dark overrides: only what differs from light. Written twice — for an explicit choice (.dark / data-theme="dark")
 * and for data-theme="system", which follows the operating system with no script (no flash on first paint). */
const darkLines = (pad) => {
  const out = [];
  for (const tier of ['semantic', 'component']) for (const [k, v] of Object.entries(T[tier].dark)) if (v !== T[tier].light[k]) out.push(`${pad}--aura-${k}: ${cssRef(v)};`);
  for (const [k, v] of Object.entries(T.shadow.dark)) if (v !== T.shadow.light[k]) out.push(`${pad}--aura-${k}: ${v};`);
  out.push(`${pad}color-scheme: dark;`);
  return out;
};
L.push('.dark, [data-theme="dark"] {', ...darkLines('  '), '}', '');
L.push('/* data-theme="system": light or dark from prefers-color-scheme. */');
L.push('@media (prefers-color-scheme: dark) {', '  [data-theme="system"] {', ...darkLines('    '), '  }', '}', '');
L.push(':root {');
for (const fam of ['spacing', 'radius', 'size', 'breakpoint', 'opacity', 'zIndex']) for (const [k, v] of Object.entries(T[fam])) L.push(`  --aura-${k}: ${v};`);
for (const [k, v] of Object.entries(T.motion.easing)) L.push(`  --aura-${k}: ${v};`);
for (const [k, v] of Object.entries(T.motion.duration)) L.push(`  --aura-${k}: ${v};`);
for (const [k, v] of Object.entries(T.typography.families)) L.push(`  --font-${k}: ${v};`);
L.push('}', '');
for (const [name, s] of Object.entries(T.typography.styles)) {
  const decl = [`font-family: var(--font-${s.family})`];
  for (const k of ['fontSize', 'lineHeight', 'fontWeight', 'letterSpacing']) if (s[k] != null) decl.push(`${kebab(k)}: ${s[k]}`);
  L.push(`.aura-text-${name} { ${decl.join('; ')}; }`);
}
fs.writeFileSync(path.join(root, 'aura.css'), L.join('\n') + '\n');

/* ---------- aura-fonts.css ---------- */
fs.writeFileSync(path.join(root, 'aura-fonts.css'),
  '/* AURA fonts from Google Fonts: Fraunces 600, Inter 400/500/600, JetBrains Mono 400, Noto Sans Thai 400/500/600. GENERATED. */\n' +
  `@import url("${T.typography.googleFonts}");\n`);

/* ---------- tailwind.tokens.cjs ---------- */
const colors = { aura: {} };
for (const [fam, scale] of Object.entries(T.primitive)) {
  if (typeof scale === 'string') colors.aura[fam] = `var(--aura-${fam})`;
  else { colors.aura[fam] = {}; for (const k of Object.keys(scale)) colors.aura[fam][k] = `var(--aura-${fam}-${k})`; }
}
const group = (prefix) => {
  const o = {};
  for (const tier of ['semantic', 'component']) for (const k of Object.keys(T[tier].light)) if (k.startsWith(prefix + '-')) o[k.slice(prefix.length + 1)] = `var(--aura-${k})`;
  return o;
};
const bg = group('bg'); bg.hover = 'var(--aura-bg-surface-hover)'; bg.strong = 'var(--aura-bg-surface-strong)'; /* 4.0 aliases */
  Object.assign(colors, { bg, fg: group('fg'), border: { DEFAULT: 'var(--aura-border-default)', ...group('border') },
  accent: group('accent'), status: group('status'), alert: group('alert'), focus: { ring: 'var(--aura-focus-ring)' } });
const tw = {
  colors,
  spacing: Object.fromEntries(Object.keys(T.spacing).map((k) => ['aura-' + k.replace(/^space-/, ''), `var(--aura-${k})`])),
  borderRadius: Object.fromEntries(Object.keys(T.radius).map((k) => ['aura-' + k.replace(/^radius-/, ''), `var(--aura-${k})`])),
  boxShadow: Object.fromEntries(Object.keys(T.shadow.light).map((k) => ['aura-' + k.replace(/^shadow-/, ''), `var(--aura-${k})`])),
  transitionTimingFunction: Object.fromEntries(Object.keys(T.motion.easing).map((k) => ['aura-' + k, `var(--aura-${k})`])),
  transitionDuration: Object.fromEntries(Object.keys(T.motion.duration).map((k) => [k.replace(/^aura-duration-|^duration-/, 'aura-'), `var(--aura-${k})`])),
  screens: Object.fromEntries(Object.entries(T.breakpoint).map(([k, v]) => [k.replace(/^bp-/, ''), v])),
  zIndex: Object.fromEntries(Object.keys(T.zIndex).map((k) => ['aura-' + k.replace(/^z-/, ''), `var(--aura-${k})`])),
  fontFamily: Object.fromEntries(Object.entries(T.typography.families).map(([k, v]) => [k, v.split(',').map((s) => s.trim().replace(/^"|"$/g, ''))])),
};
fs.writeFileSync(path.join(root, 'tailwind.tokens.cjs'),
  '/* GENERATED by scripts/build-tokens.js from tokens.json. Do not edit by hand. */\nmodule.exports = ' + JSON.stringify(tw, null, 2) + ';\n');

/* ---------- figma-variables.csv ---------- */
const rows = [['name', 'type', 'mode', 'value', 'description', 'scope']];
const note = (k) => (T.notes && T.notes[k] ? T.notes[k].replace(/"/g, "'") : '');
for (const [fam, scale] of Object.entries(T.primitive)) {
  if (typeof scale === 'string') rows.push([`primitive/${fam}`, 'color', 'light', scale, note(fam), '']);
  else for (const [k, v] of Object.entries(scale)) rows.push([`primitive/${fam}/${k}`, 'color', 'light', v, note(`${fam}-${k}`), '']);
}
const scopeOf = (k) => (k.startsWith('bg-') ? 'FRAME_FILL' : k.startsWith('fg-') ? 'TEXT_FILL' : k.startsWith('border-') ? 'STROKE_COLOR' : 'ALL_FILLS');
for (const tier of ['semantic', 'component']) for (const mode of ['light', 'dark']) for (const [k, v] of Object.entries(T[tier][mode]))
  rows.push([`${tier}/${k}`, 'color', mode, figmaRef(v), note(k), scopeOf(k)]);
for (const fam of ['spacing', 'radius', 'size']) for (const [k, v] of Object.entries(T[fam])) rows.push([`${fam}/${k}`, 'number', 'light', px(v), note(k), fam === 'radius' ? 'CORNER_RADIUS' : 'GAP']);
const csv = rows.map((r) => r.map((c) => (/[",\n]/.test(c) ? `"${String(c).replace(/"/g, '""')}"` : c)).join(',')).join('\n');
fs.writeFileSync(path.join(root, 'figma-variables.csv'), csv + '\n');

console.log(`AURA ${T.version}: aura.css, aura-fonts.css, tailwind.tokens.cjs, figma-variables.csv written (${rows.length - 1} Figma variables).`);
