#!/usr/bin/env node
/* Build every token output from tokens.json (the single source of truth).
 *   aura-fonts.css       the Google Fonts @import (kept apart so a blocked font host can't break aura.css)
 *   aura.css             CSS variables: light on :root / [data-theme="light"], dark on .dark / [data-theme="dark"],
 *                        and data-theme="system" follows prefers-color-scheme
 *   tailwind.tokens.cjs  the maps tailwind.config.ts spreads into theme.extend
 *   aura-tailwind.css    the same class names for Tailwind v4 (CSS-first: @import it after tailwindcss)
 *   figma-variables.csv  every colour for both modes + numbers, for a Variables Import plugin
 * Usage: node scripts/build-tokens.js   (npm run build:tokens) */
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const T = JSON.parse(fs.readFileSync(path.join(root, 'tokens.json'), 'utf8'));

const kebab = (s) => String(s).replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
const cssRef = (v) => String(v).replace(/\{primitive\.([a-z]+)(?:\.(\d+))?\}/g, (_, a, b) => `var(--aura-${a}${b ? '-' + b : ''})`)
  .replace(/\{(?:semantic|component)\.([a-z0-9-]+)\}/g, (_, a) => `var(--aura-${a})`);
const figmaRef = (v) => String(v).replace(/\{primitive\.([a-z]+)(?:\.(\d+))?\}/g, (_, a, b) => `{primitive/${a}${b ? '/' + b : ''}}`)
  .replace(/\{(semantic|component)\.([a-z0-9-]+)\}/g, (_, t, a) => `{${t}/${a}}`);
const px = (v) => String(v).replace(/px$/, '');

/* ---------- aura.css ---------- */
const L = [];
L.push('/* AURA v' + T.version + ' — GENERATED by scripts/build-tokens.js from tokens.json. Do not edit by hand. */');
L.push('/* Fonts: load aura-fonts.css (or the <link> tags in README) separately, so a blocked Google Fonts never breaks this file. */', '');
L.push(':root, [data-theme="light"] {');
for (const [fam, scale] of Object.entries(T.primitive)) {
  if (typeof scale === 'string') L.push(`  --aura-${fam}: ${scale};`);
  else for (const [k, v] of Object.entries(scale)) L.push(`  --aura-${fam}-${k}: ${v};`);
}
for (const tier of ['semantic', 'component']) for (const [k, v] of Object.entries(T[tier].light)) L.push(`  --aura-${k}: ${cssRef(v)};`);
for (const [k, v] of Object.entries(T.shadow.light)) L.push(`  --aura-${k}: ${v};`);
L.push('  color-scheme: light;', '}', '');
/* Dark overrides: only what differs from light. Written twice — for an explicit choice (.dark / data-theme="dark")
 * and for data-theme="system", which follows the operating system with no script (no flash on first paint). */
const darkLines = (pad) => {
  const out = [];
  for (const tier of ['semantic', 'component']) for (const [k, v] of Object.entries(T[tier].dark)) if (v !== T[tier].light[k]) out.push(`${pad}--aura-${k}: ${cssRef(v)};`);
  for (const [k, v] of Object.entries(T.shadow.dark)) if (v !== T.shadow.light[k]) out.push(`${pad}--aura-${k}: ${v};`);
  out.push(`${pad}color-scheme: dark;`);
  return out;
};
L.push('.dark, [data-theme="dark"] {', ...darkLines('  '), '}', '');
L.push('/* data-theme="system": light or dark from prefers-color-scheme. */');
L.push('@media (prefers-color-scheme: dark) {', '  [data-theme="system"] {', ...darkLines('    '), '  }', '}', '');
L.push(':root {');
for (const fam of ['spacing', 'radius', 'size', 'breakpoint', 'opacity', 'zIndex']) for (const [k, v] of Object.entries(T[fam])) L.push(`  --aura-${k}: ${v};`);
for (const [k, v] of Object.entries(T.motion.easing)) L.push(`  --aura-${k}: ${v};`);
for (const [k, v] of Object.entries(T.motion.duration)) L.push(`  --aura-${k}: ${v};`);
for (const [k, v] of Object.entries(T.typography.families)) L.push(`  --font-${k}: ${v};`);
L.push('}', '');
for (const [name, s] of Object.entries(T.typography.styles)) {
  const decl = [`font-family: var(--font-${s.family})`];
  for (const k of ['fontSize', 'lineHeight', 'fontWeight', 'letterSpacing']) if (s[k] != null) decl.push(`${kebab(k)}: ${s[k]}`);
  L.push(`.aura-text-${name} { ${decl.join('; ')}; }`);
}
fs.writeFileSync(path.join(root, 'aura.css'), L.join('\n') + '\n');

/* ---------- aura-fonts.css ---------- */
fs.writeFileSync(path.join(root, 'aura-fonts.css'),
  '/* AURA fonts from Google Fonts: Fraunces 600, Inter 400/500/600, JetBrains Mono 400, Noto Sans Thai 400/500/600. GENERATED. */\n' +
  `@import url("${T.typography.googleFonts}");\n`);

/* ---------- aura-fonts.local.css (4.16) ----------
 * Self-hosted: the same four families as woff2 files in ./fonts (Fontsource 5.3.0, OFL-1.1), for apps whose CSP
 * allows only font-src 'self'. Split by unicode-range, so a page downloads only the subsets it uses. */
const RANGE = { latin: "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD", latinExt: "U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF", thai: "U+02D7,U+0303,U+0331,U+0E01-0E5B,U+200C-200D,U+25CC" };
const FACES = [
  ['Fraunces', '100 900', 'fraunces-latin-opsz-normal', RANGE.latin],
  ['Fraunces', '100 900', 'fraunces-latin-ext-opsz-normal', RANGE.latinExt],
  ['Inter', '100 900', 'inter-latin-wght-normal', RANGE.latin],
  ['Inter', '100 900', 'inter-latin-ext-wght-normal', RANGE.latinExt],
  ['JetBrains Mono', '400', 'jetbrains-mono-latin-400-normal', RANGE.latin],
  ['JetBrains Mono', '400', 'jetbrains-mono-latin-ext-400-normal', RANGE.latinExt],
  ['Noto Sans Thai', '100 900', 'noto-sans-thai-thai-wght-normal', RANGE.thai],
];
fs.writeFileSync(path.join(root, 'aura-fonts.local.css'),
  '/* AURA fonts, self-hosted: Fraunces, Inter, JetBrains Mono and Noto Sans Thai from ./fonts (OFL-1.1, see fonts/LICENSE.md).\n' +
  ' * Use instead of aura-fonts.css when your CSP allows only font-src \'self\'. GENERATED. */\n' +
  FACES.map(([family, weight, file, range]) =>
    `@font-face {\n  font-family: "${family}";\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: swap;\n  src: url("./fonts/${file}.woff2") format("woff2");\n  unicode-range: ${range};\n}`).join('\n') + '\n');

/* ---------- tailwind.tokens.cjs ---------- */
const colors = { aura: {} };
for (const [fam, scale] of Object.entries(T.primitive)) {
  if (typeof scale === 'string') colors.aura[fam] = `var(--aura-${fam})`;
  else { colors.aura[fam] = {}; for (const k of Object.keys(scale)) colors.aura[fam][k] = `var(--aura-${fam}-${k})`; }
}
const group = (prefix) => {
  const o = {};
  for (const tier of ['semantic', 'component']) for (const k of Object.keys(T[tier].light)) if (k.startsWith(prefix + '-')) o[k.slice(prefix.length + 1)] = `var(--aura-${k})`;
  return o;
};
const bg = group('bg'); bg.hover = 'var(--aura-bg-surface-hover)'; bg.strong = 'var(--aura-bg-surface-strong)'; /* 4.0 aliases */
  Object.assign(colors, { bg, fg: group('fg'), border: { DEFAULT: 'var(--aura-border-default)', ...group('border') },
  accent: group('accent'), status: group('status'), chart: group('chart'), alert: group('alert'), focus: { ring: 'var(--aura-focus-ring)' } });
const tw = {
  colors,
  spacing: Object.fromEntries(Object.keys(T.spacing).map((k) => ['aura-' + k.replace(/^space-/, ''), `var(--aura-${k})`])),
  borderRadius: Object.fromEntries(Object.keys(T.radius).map((k) => ['aura-' + k.replace(/^radius-/, ''), `var(--aura-${k})`])),
  boxShadow: Object.fromEntries(Object.keys(T.shadow.light).map((k) => ['aura-' + k.replace(/^shadow-/, ''), `var(--aura-${k})`])),
  transitionTimingFunction: Object.fromEntries(Object.keys(T.motion.easing).map((k) => ['aura-' + k, `var(--aura-${k})`])),
  transitionDuration: Object.fromEntries(Object.keys(T.motion.duration).map((k) => [k.replace(/^aura-duration-|^duration-/, 'aura-'), `var(--aura-${k})`])),
  screens: Object.fromEntries(Object.entries(T.breakpoint).map(([k, v]) => [k.replace(/^bp-/, ''), v])),
  zIndex: Object.fromEntries(Object.keys(T.zIndex).map((k) => ['aura-' + k.replace(/^z-/, ''), `var(--aura-${k})`])),
  fontFamily: Object.fromEntries(Object.entries(T.typography.families).map(([k, v]) => [k, v.split(',').map((s) => s.trim().replace(/^"|"$/g, ''))])),
};
fs.writeFileSync(path.join(root, 'tailwind.tokens.cjs'),
  '/* GENERATED by scripts/build-tokens.js from tokens.json. Do not edit by hand. */\nmodule.exports = ' + JSON.stringify(tw, null, 2) + ';\n');

/* ---------- aura-tailwind.css (Tailwind v4) ----------
 * Same class names as the v3 preset above. `@theme inline` makes utilities point at the --aura-* variables directly,
 * so .dark / data-theme switch them with no dark: prefixes. Fonts use `inline reference`: Tailwind's --font-* names
 * are the ones aura.css already sets, so re-declaring them would make a self-reference. */
const flat = (obj, pre, out) => {
  for (const [k, v] of Object.entries(obj)) {
    const name = k === 'DEFAULT' ? pre : pre + '-' + k;
    if (typeof v === 'string') out.push(`  --color${name}: ${v};`);
    else flat(v, name, out);
  }
  return out;
};
const V4 = ['/* AURA v' + T.version + ' — Tailwind v4 theme. GENERATED by scripts/build-tokens.js from tokens.json. Do not edit by hand.',
  ' *   @import "tailwindcss";',
  ' *   @import "@jirawatpyk/aura-tokens/tailwind.css";',
  ' * Gives bg-bg-surface, text-fg-primary, border-border-strong, p-aura-6, rounded-aura-xl, shadow-aura-overlay,',
  ' * ease-aura-ease, duration-aura-fast, z-aura-dialog, font-display … (the v3 preset\'s names). */',
  '@import "./aura.css";', '',
  '/* dark: follows .dark and data-theme="dark", the same switches aura.css uses. */',
  '@custom-variant dark (&:where(.dark, .dark *, [data-theme="dark"], [data-theme="dark"] *));', '',
  '@theme inline {'];
flat(tw.colors, '', V4);
for (const [k, v] of Object.entries(tw.spacing)) V4.push(`  --spacing-${k}: ${v};`);
for (const [k, v] of Object.entries(tw.borderRadius)) V4.push(`  --radius-${k}: ${v};`);
for (const [k, v] of Object.entries(tw.boxShadow)) V4.push(`  --shadow-${k}: ${v};`);
for (const [k, v] of Object.entries(tw.transitionTimingFunction)) V4.push(`  --ease-${k}: ${v};`);
V4.push('}', '', '@theme inline reference {');
for (const k of Object.keys(T.typography.families)) V4.push(`  --font-${k}: var(--font-${k});`);
V4.push('}', '', '/* Tailwind v4 has no theme keys for durations or z-index, so these are plain utilities. */');
for (const [k, v] of Object.entries(tw.transitionDuration)) V4.push(`@utility duration-${k} { transition-duration: ${v}; }`);
for (const [k, v] of Object.entries(tw.zIndex)) V4.push(`@utility z-${k} { z-index: ${v}; }`);
fs.writeFileSync(path.join(root, 'aura-tailwind.css'), V4.join('\n') + '\n');

/* ---------- aura-tailwind.prefixed.css (4.17) ----------
 * For apps that migrate page by page next to another theme (shadcn): every theme name carries `aura-`
 * (bg-aura-bg-surface, border-aura-border-strong, font-aura-sans), fonts are the literal stacks, and there is no
 * @custom-variant and no @import, so nothing an existing page uses is redefined. aura.css is imported by the app in
 * an early layer (see the header). */
const P = ['/* AURA v' + T.version + ' — Tailwind v4 theme with aura- prefixed names. GENERATED by scripts/build-tokens.js. Do not edit by hand.',
  ' * For apps that already have a Tailwind theme (shadcn): nothing here redefines an existing name.',
  ' *   @layer aura-tokens, theme, base, aura, components, utilities;',
  ' *   @import "tailwindcss";',
  ' *   @import "@jirawatpyk/aura-tokens/aura.css" layer(aura-tokens);   <- the --aura-* variables; your theme wins for --font-*',
  ' *   @import "@jirawatpyk/aura-tokens/tailwind.prefixed.css";',
  ' *   @import "@jirawatpyk/aura-react/styles.layer.css";                <- components in @layer aura, so utilities win',
  ' * Classes: bg-aura-bg-surface, text-aura-fg-primary, border-aura-border-strong, bg-aura-chart-1, p-aura-6,',
  ' * rounded-aura-xl, shadow-aura-overlay, font-aura-sans … Use your own dark: variant. */', '', '@theme inline {'];
const pre = (line) => line.replace(/^  --color-(?!aura-)/, '  --color-aura-');
flat(tw.colors, '', []).forEach((l) => P.push(pre(l)));
for (const [k, v] of Object.entries(tw.spacing)) P.push(`  --spacing-${k}: ${v};`);
for (const [k, v] of Object.entries(tw.borderRadius)) P.push(`  --radius-${k}: ${v};`);
for (const [k, v] of Object.entries(tw.boxShadow)) P.push(`  --shadow-${k}: ${v};`);
for (const [k, v] of Object.entries(tw.transitionTimingFunction)) P.push(`  --ease-${k}: ${v};`);
for (const [k, v] of Object.entries(T.typography.families)) P.push(`  --font-aura-${k}: ${v};`);
P.push('}', '');
for (const [k, v] of Object.entries(tw.transitionDuration)) P.push(`@utility duration-${k} { transition-duration: ${v}; }`);
for (const [k, v] of Object.entries(tw.zIndex)) P.push(`@utility z-${k} { z-index: ${v}; }`);
const bad = P.filter((l) => /^  --(color|font)-(?!aura-)/.test(l));
if (bad.length) throw new Error('aura-tailwind.prefixed.css has unprefixed names: ' + bad.join(' '));
fs.writeFileSync(path.join(root, 'aura-tailwind.prefixed.css'), P.join('\n') + '\n');

/* ---------- figma-variables.csv ---------- */
const rows = [['name', 'type', 'mode', 'value', 'description', 'scope']];
const note = (k) => (T.notes && T.notes[k] ? T.notes[k].replace(/"/g, "'") : '');
for (const [fam, scale] of Object.entries(T.primitive)) {
  if (typeof scale === 'string') rows.push([`primitive/${fam}`, 'color', 'light', scale, note(fam), '']);
  else for (const [k, v] of Object.entries(scale)) rows.push([`primitive/${fam}/${k}`, 'color', 'light', v, note(`${fam}-${k}`), '']);
}
const scopeOf = (k) => (k.startsWith('bg-') ? 'FRAME_FILL' : k.startsWith('fg-') ? 'TEXT_FILL' : k.startsWith('border-') ? 'STROKE_COLOR' : 'ALL_FILLS');
for (const tier of ['semantic', 'component']) for (const mode of ['light', 'dark']) for (const [k, v] of Object.entries(T[tier][mode]))
  rows.push([`${tier}/${k}`, 'color', mode, figmaRef(v), note(k), scopeOf(k)]);
for (const fam of ['spacing', 'radius', 'size']) for (const [k, v] of Object.entries(T[fam])) rows.push([`${fam}/${k}`, 'number', 'light', px(v), note(k), fam === 'radius' ? 'CORNER_RADIUS' : 'GAP']);
const csv = rows.map((r) => r.map((c) => (/[",\n]/.test(c) ? `"${String(c).replace(/"/g, '""')}"` : c)).join(',')).join('\n');
fs.writeFileSync(path.join(root, 'figma-variables.csv'), csv + '\n');

console.log(`AURA ${T.version}: aura.css, aura-fonts.css, aura-fonts.local.css, tailwind.tokens.cjs, aura-tailwind.css, aura-tailwind.prefixed.css, figma-variables.csv written (${rows.length - 1} Figma variables).`);
