/* GENERATED by scripts/build-tokens.js from tokens.json. Do not edit by hand. */
module.exports = {
  "colors": {
    "aura": {
      "violet": {
        "50": "var(--aura-violet-50)",
        "100": "var(--aura-violet-100)",
        "200": "var(--aura-violet-200)",
        "300": "var(--aura-violet-300)",
        "400": "var(--aura-violet-400)",
        "500": "var(--aura-violet-500)",
        "600": "var(--aura-violet-600)",
        "700": "var(--aura-violet-700)",
        "800": "var(--aura-violet-800)",
        "900": "var(--aura-violet-900)"
      },
      "zinc": {
        "0": "var(--aura-zinc-0)",
        "50": "var(--aura-zinc-50)",
        "100": "var(--aura-zinc-100)",
        "200": "var(--aura-zinc-200)",
        "300": "var(--aura-zinc-300)",
        "400": "var(--aura-zinc-400)",
        "450": "var(--aura-zinc-450)",
        "500": "var(--aura-zinc-500)",
        "600": "var(--aura-zinc-600)",
        "700": "var(--aura-zinc-700)",
        "800": "var(--aura-zinc-800)",
        "900": "var(--aura-zinc-900)",
        "950": "var(--aura-zinc-950)"
      },
      "lime": {
        "50": "var(--aura-lime-50)",
        "100": "var(--aura-lime-100)",
        "200": "var(--aura-lime-200)",
        "300": "var(--aura-lime-300)",
        "400": "var(--aura-lime-400)",
        "500": "var(--aura-lime-500)",
        "600": "var(--aura-lime-600)",
        "800": "var(--aura-lime-800)"
      },
      "red": {
        "50": "var(--aura-red-50)",
        "200": "var(--aura-red-200)",
        "300": "var(--aura-red-300)",
        "400": "var(--aura-red-400)",
        "600": "var(--aura-red-600)",
        "700": "var(--aura-red-700)",
        "800": "var(--aura-red-800)"
      },
      "amber": {
        "50": "var(--aura-amber-50)",
        "200": "var(--aura-amber-200)",
        "300": "var(--aura-amber-300)",
        "800": "var(--aura-amber-800)"
      },
      "ink": "var(--aura-ink)",
      "white": "var(--aura-white)"
    },
    "bg": {
      "surface": "var(--aura-bg-surface)",
      "surface-hover": "var(--aura-bg-surface-hover)",
      "surface-strong": "var(--aura-bg-surface-strong)",
      "canvas": "var(--aura-bg-canvas)",
      "inverted": "var(--aura-bg-inverted)",
      "selected": "var(--aura-bg-selected)",
      "skeleton": "var(--aura-bg-skeleton)",
      "input": "var(--aura-bg-input)",
      "input-disabled": "var(--aura-bg-input-disabled)",
      "scrim": "var(--aura-bg-scrim)",
      "hover": "var(--aura-bg-surface-hover)",
      "strong": "var(--aura-bg-surface-strong)"
    },
    "fg": {
      "primary": "var(--aura-fg-primary)",
      "secondary": "var(--aura-fg-secondary)",
      "tertiary": "var(--aura-fg-tertiary)",
      "inverted": "var(--aura-fg-inverted)",
      "accent": "var(--aura-fg-accent)",
      "danger": "var(--aura-fg-danger)",
      "positive": "var(--aura-fg-positive)"
    },
    "border": {
      "DEFAULT": "var(--aura-border-default)",
      "default": "var(--aura-border-default)",
      "strong": "var(--aura-border-strong)",
      "subtle": "var(--aura-border-subtle)",
      "control": "var(--aura-border-control)",
      "danger": "var(--aura-border-danger)"
    },
    "accent": {
      "dot": "var(--aura-accent-dot)",
      "violet": "var(--aura-accent-violet)",
      "lime": "var(--aura-accent-lime)"
    },
    "status": {
      "neutral-bg": "var(--aura-status-neutral-bg)",
      "neutral-fg": "var(--aura-status-neutral-fg)",
      "progress-bg": "var(--aura-status-progress-bg)",
      "progress-fg": "var(--aura-status-progress-fg)",
      "ready-bg": "var(--aura-status-ready-bg)",
      "ready-fg": "var(--aura-status-ready-fg)",
      "blocked-bg": "var(--aura-status-blocked-bg)",
      "blocked-fg": "var(--aura-status-blocked-fg)"
    },
    "chart": {
      "1": "var(--aura-chart-1)",
      "2": "var(--aura-chart-2)",
      "3": "var(--aura-chart-3)",
      "4": "var(--aura-chart-4)",
      "5": "var(--aura-chart-5)",
      "6": "var(--aura-chart-6)",
      "7": "var(--aura-chart-7)",
      "8": "var(--aura-chart-8)",
      "seq-1": "var(--aura-chart-seq-1)",
      "seq-2": "var(--aura-chart-seq-2)",
      "seq-3": "var(--aura-chart-seq-3)",
      "seq-4": "var(--aura-chart-seq-4)",
      "seq-5": "var(--aura-chart-seq-5)",
      "grid": "var(--aura-chart-grid)",
      "axis": "var(--aura-chart-axis)"
    },
    "alert": {
      "info-bg": "var(--aura-alert-info-bg)",
      "info-fg": "var(--aura-alert-info-fg)",
      "info-border": "var(--aura-alert-info-border)",
      "success-bg": "var(--aura-alert-success-bg)",
      "success-fg": "var(--aura-alert-success-fg)",
      "success-border": "var(--aura-alert-success-border)",
      "warning-bg": "var(--aura-alert-warning-bg)",
      "warning-fg": "var(--aura-alert-warning-fg)",
      "warning-border": "var(--aura-alert-warning-border)",
      "danger-bg": "var(--aura-alert-danger-bg)",
      "danger-fg": "var(--aura-alert-danger-fg)",
      "danger-border": "var(--aura-alert-danger-border)"
    },
    "focus": {
      "ring": "var(--aura-focus-ring)"
    }
  },
  "spacing": {
    "aura-0": "var(--aura-space-0)",
    "aura-1": "var(--aura-space-1)",
    "aura-2": "var(--aura-space-2)",
    "aura-3": "var(--aura-space-3)",
    "aura-4": "var(--aura-space-4)",
    "aura-5": "var(--aura-space-5)",
    "aura-6": "var(--aura-space-6)",
    "aura-8": "var(--aura-space-8)",
    "aura-10": "var(--aura-space-10)",
    "aura-12": "var(--aura-space-12)",
    "aura-16": "var(--aura-space-16)",
    "aura-card-padding": "var(--aura-card-padding)"
  },
  "borderRadius": {
    "aura-xs": "var(--aura-radius-xs)",
    "aura-sm": "var(--aura-radius-sm)",
    "aura-md": "var(--aura-radius-md)",
    "aura-lg": "var(--aura-radius-lg)",
    "aura-xl": "var(--aura-radius-xl)",
    "aura-2xl": "var(--aura-radius-2xl)",
    "aura-full": "var(--aura-radius-full)",
    "aura-squircle": "var(--aura-radius-squircle)",
    "aura-card-radius": "var(--aura-card-radius)",
    "aura-button-radius": "var(--aura-button-radius)"
  },
  "boxShadow": {
    "aura-enterprise": "var(--aura-shadow-enterprise)",
    "aura-overlay": "var(--aura-shadow-overlay)",
    "aura-creative": "var(--aura-shadow-creative)",
    "aura-creative-hover": "var(--aura-shadow-creative-hover)",
    "aura-card-shadow-creative": "var(--aura-card-shadow-creative)"
  },
  "transitionTimingFunction": {
    "aura-ease": "var(--aura-ease)",
    "aura-spring": "var(--aura-spring)"
  },
  "transitionDuration": {
    "aura-fast": "var(--aura-duration-fast)",
    "aura-base": "var(--aura-duration-base)",
    "aura-slow": "var(--aura-duration-slow)",
    "aura-spin": "var(--aura-duration-spin)",
    "aura-pulse": "var(--aura-duration-pulse)",
    "aura-toast": "var(--aura-duration-toast)",
    "aura-tooltip": "var(--aura-duration-tooltip)"
  },
  "screens": {
    "sm": "640px",
    "md": "768px",
    "lg": "1024px",
    "xl": "1280px"
  },
  "zIndex": {
    "aura-menu": "var(--aura-z-menu)",
    "aura-dialog": "var(--aura-z-dialog)",
    "aura-bar": "var(--aura-z-bar)",
    "aura-toast": "var(--aura-z-toast)",
    "aura-tooltip": "var(--aura-z-tooltip)"
  },
  "fontFamily": {
    "display": [
      "Fraunces",
      "Noto Sans Thai",
      "serif"
    ],
    "sans": [
      "Inter",
      "Noto Sans Thai",
      "sans-serif"
    ],
    "mono": [
      "JetBrains Mono",
      "monospace"
    ],
    "thai": [
      "Noto Sans Thai",
      "sans-serif"
    ]
  }
};
